# General Jekyll Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
url: http://kevinguebert.github.io
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
